spring:
  application:
    #    服务名称
    name:
      file-service-consumer
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 2048MB
      max-request-size: 2048MB

# 服务运行端口
server:
  port: 8606

#dubbo config properties
dubbo:
  scan:
    base-packages: com.example.group11.controller.file
  application:
    id: com.example.group11.controller.file
    name: com.example.group11.controller.file
  protocol:
    id: dubbo
    name: dubbo
  registry:
    id: zookeeper
    #    zookeeper运行端口
    address: zookeeper://172.30.229.165:2181

