spring:
  application:
    #    服务名称
    name:
      qa-service-provider
  #    数据库连接信息
  datasource:
    url: jdbc:mysql://group11-database-do-user-14640959-0.b.db.ondigitalocean.com:25060/defaultdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=true
    username: doadmin
    password: AVNS_UeUmefIueMk-xarcAHd
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 2048MB
      max-request-size: 2048MB

# 服务运行端口
server:
  port: 8503

#dubbo config properties
dubbo:
  scan:
    base-packages: com.example.group11.service.qa.impl
  application:
    id: com.example.group11.service.qa
    name: com.example.group11.service.qa
  protocol:
    id: dubbo
    name: dubbo
    #    dubbo端口
    port: 20883
  registry:
    id: zookeeper
    #    zookeeper运行端口
    address: zookeeper://127.0.0.1:2181

