spring:
  application:
    #    服务名称
    name:
      qa-service-consumer
  datasource:
    url: jdbc:mysql://group11-database-do-user-14640959-0.b.db.ondigitalocean.com:25060/defaultdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=true
    username: doadmin
    password: AVNS_UeUmefIueMk-xarcAHd
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 2048MB
      max-request-size: 2048MB
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  redis:
    host: 39.107.136.24
    port: 6379
    password: Jenkins@0101



# 服务运行端口
server:
  port: 8603

#dubbo config properties
dubbo:
  scan:
    base-packages: com.example.group11.controller.qa
  application:
    id: com.example.group11.controller.qa
    name: com.example.group11.controller.qa
  protocol:
    id: dubbo
    name: dubbo
    serialization: kryo
  registry:
    id: zookeeper
    #    zookeeper运行端口
    address: zookeeper://172.24.84.138:2181

