name: CI to Docker Hub
on:
  push:
    branches: [ master ]  # 触发工作流程的分支，这里设置为 main 分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'


    - name: Build with Maven
      run: mvn -B package --file ./commons/pom.xml

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3 
      with:
        username: bigidea
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push provider
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: ./commons/qa-service-provider
        push: true
        tags: bigidea/service-provider:latest

    - name: Build and Push consumer
      id: docker_build_consumer
      uses: docker/build-push-action@v5
      with:
        context: ./commons/qa-service-consumer
        push: true
        tags: bigidea/service-consumer:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
