apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-provider
  labels:
    app: user-service-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-provider
  template:
    metadata:
      labels:
        app: user-service-provider    
    spec:
      containers:
      - name: user-service-provider
        image: 172.30.229.165/group11-dubbo-node2/user-service-provider:imageVersion
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service-provider
  name: user-service-provider  
spec:
  selector:
    app: user-service-provider
  ports:
  - port: 8502
    targetPort: 8502
